export enum EEmployeeThunkActions {
  EMPLOYEE = 'EMPLOYEE',
  GET_EMPLOYEE = 'GET_EMPLOYEE',
  DELETE_EMPLOYEE = 'DELETE_EMPLOY',
  CREATE_EMPLOYEE = 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE',
}
