export const initialValuesEmployeeInformation = {
  name: '',
  mother_name: '',
  gender: '',
  dob: '',
  pob: '',
  nc_id: undefined,
  ktp_no: undefined,
  home_address_1: '',
  home_address_2: '',
  mobile_no: undefined,
  tel_no: undefined,
  marriage_id: '',
  card_number: undefined,
  bank_account_no: undefined,
  bank_name: '',
  family_card_number: undefined,
  safety_insurance_no: undefined,
  health_insurance_no: undefined,
};
